directive set /top/fir/fir:run/run/main-1:MAC:i:slc(MAC:i(3:0))(2-0).itm.1 REGISTER_NAME main-1:MAC:i:slc(MAC:i(3:0))(2-0).itm.1
directive set /top/fir/fir:run/run/main-2:MAC:i:slc(MAC:i(3:0))(2-0)#1.itm.1 REGISTER_NAME main-1:MAC:i:slc(MAC:i(3:0))(2-0).itm.1
directive set /top/fir/fir:run/run/main-1:SHIFT:i:slc(SHIFT:i(3:0))(2-0)#3.itm.1 REGISTER_NAME main-1:SHIFT:i:slc(SHIFT:i(3:0))(2-0)#3.itm.1
directive set /top/fir/fir:run/run/main-2:SHIFT:i:slc(SHIFT:i(3:0))(2-0)#3.itm.1 REGISTER_NAME main-1:SHIFT:i:slc(SHIFT:i(3:0))(2-0)#3.itm.1
directive set /top/fir/fir:run/run/SHIFT:and#1.svs.st.1 REGISTER_NAME SHIFT:and#1.svs.st.1
directive set /top/fir/fir:run/run/SHIFT:and.svs.st.1 REGISTER_NAME SHIFT:and#1.svs.st.1
directive set /top/fir/fir:run/run/regs(1).sva.dfm#1.1 REGISTER_NAME regs(1).sva.dfm#1.1
directive set /top/fir/fir:run/run/regs(1).sva.dfm.1 REGISTER_NAME regs(1).sva.dfm#1.1
directive set /top/fir/fir:run/run/regs(2).sva.dfm#1.1 REGISTER_NAME regs(2).sva.dfm#1.1
directive set /top/fir/fir:run/run/regs(2).sva.dfm.1 REGISTER_NAME regs(2).sva.dfm#1.1
directive set /top/fir/fir:run/run/regs(3).sva.dfm#1.1 REGISTER_NAME regs(3).sva.dfm#1.1
directive set /top/fir/fir:run/run/regs(3).sva.dfm.1 REGISTER_NAME regs(3).sva.dfm#1.1
directive set /top/fir/fir:run/run/regs(4).sva.dfm#1.1 REGISTER_NAME regs(4).sva.dfm#1.1
directive set /top/fir/fir:run/run/regs(4).sva.dfm.1 REGISTER_NAME regs(4).sva.dfm#1.1
directive set /top/fir/fir:run/run/regs(5).sva.dfm#1.1 REGISTER_NAME regs(5).sva.dfm#1.1
directive set /top/fir/fir:run/run/regs(5).sva.dfm.1 REGISTER_NAME regs(5).sva.dfm#1.1
directive set /top/fir/fir:run/run/regs(6).sva.dfm#1.1 REGISTER_NAME regs(6).sva.dfm#1.1
directive set /top/fir/fir:run/run/regs(6).sva.dfm.1 REGISTER_NAME regs(6).sva.dfm#1.1
directive set /top/fir/fir:run/run/regs(7).sva.dfm#1.1 REGISTER_NAME regs(7).sva.dfm#1.1
directive set /top/fir/fir:run/run/regs(7).sva.dfm.1 REGISTER_NAME regs(7).sva.dfm#1.1
directive set /top/fir/fir:run/run/SHIFT:unequal.tmp#1.1 REGISTER_NAME SHIFT:unequal.tmp#1.1
directive set /top/fir/fir:run/run/SHIFT:unequal.tmp.1 REGISTER_NAME SHIFT:unequal.tmp#1.1
directive set /top/fir/fir:run/run/SHIFT:i(3:0)#1.lpi#1(2:0) REGISTER_NAME SHIFT:i(3:0)#1.lpi#1(2:0)
directive set /top/fir/fir:run/run/SHIFT:i(3:0).lpi#1(2:0) REGISTER_NAME SHIFT:i(3:0)#1.lpi#1(2:0)
directive set /top/fir/fir:run/run/SHIFT:and#1.svs REGISTER_NAME SHIFT:and#1.svs
directive set /top/fir/fir:run/run/SHIFT:and.svs.1 REGISTER_NAME SHIFT:and#1.svs
directive set /top/fir/fir:run/run/MAC:i(3:0)#1.lpi#1(2:0) REGISTER_NAME MAC:i(3:0)#1.lpi#1(2:0)
directive set /top/fir/fir:run/run/MAC:i(3:0).lpi#1(2:0) REGISTER_NAME MAC:i(3:0)#1.lpi#1(2:0)
