directive set /top/fir/fir:run/fir:run:conc/MAC-4:mul RESOURCE_NAME MAC-1:mul:rg
directive set /top/fir/fir:run/fir:run:conc/MAC-2:mul RESOURCE_NAME MAC-1:mul:rg
directive set /top/fir/fir:run/fir:run:conc/MAC-7:mul RESOURCE_NAME MAC-1:mul:rg
directive set /top/fir/fir:run/fir:run:conc/MAC-5:mul RESOURCE_NAME MAC-1:mul:rg
directive set /top/fir/fir:run/fir:run:conc/MAC-3:mul RESOURCE_NAME MAC-1:mul:rg
directive set /top/fir/fir:run/fir:run:conc/MAC-8:mul RESOURCE_NAME MAC-1:mul:rg
directive set /top/fir/fir:run/fir:run:conc/MAC-6:mul RESOURCE_NAME MAC-1:mul:rg
directive set /top/fir/fir:run/fir:run:conc/MAC-1:mul RESOURCE_NAME MAC-1:mul:rg
directive set /top/fir/fir:run/fir:run:conc/MAC:acc#4 RESOURCE_NAME MAC:acc#4:rg
directive set /top/fir/fir:run/fir:run:conc/MAC:acc#6 RESOURCE_NAME MAC:acc#4:rg
directive set /top/fir/fir:run/fir:run:conc/MAC:acc#5 RESOURCE_NAME MAC:acc#4:rg
directive set /top/fir/fir:run/fir:run:conc/MAC:acc#7 RESOURCE_NAME MAC:acc#4:rg
directive set /top/fir/fir:run/fir:run:conc/MAC:acc RESOURCE_NAME MAC:acc:rg
directive set /top/fir/fir:run/fir:run:conc/MAC:acc#8 RESOURCE_NAME MAC:acc:rg
